definitions:
  emotebox.Status:
    description: Default Status Object for presentation
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        maxLength: 20
        minLength: 4
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/status:
    get:
      description: get status of app
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/emotebox.Status'
      summary: Gives the default status of the app
      tags:
      - status
swagger: "2.0"
